version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - .:/code
    ports:
      - "3001:3000"
    depends_on:
      - db
  db:
    image: postgres:11

    environment: 
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data