version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
  db:
    image: postgres:11