# Generated by Django 3.1.1 on 2020-09-12 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='release_date',
            new_name='release',
        ),
    ]
